name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  call-workflow:
    uses: Gustry/lizmap-mapbuilder-module/.github/workflows/test-lint-css.yml@master
